ARG JDK_VERSION=8

FROM adoptopenjdk/openjdk${JDK_VERSION}:alpine-slim

COPY install-sbt.sh /tmp

ARG SBT_VERSION=1.3.6

RUN \
  apk add --no-cache --virtual .deps curl && \
  apk add --no-cache bash && \
  /tmp/install-sbt.sh ${SBT_VERSION} && \
  rm -f /tmp/install-sbt.sh && \
  apk del --purge .deps && \
  rm -rf /var/cache/apk/* && \
  sbt sbtVersion

CMD sbt
