name: Update

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - id: latest
        name: Check latest version
        run: |
          LATEST=$(curl -s https://api.github.com/repos/sbt/sbt/releases/latest | jq .tag_name)

          # Strip "v" prefix from tag name
          LATEST=$(echo $LATEST | sed -e 's/"//g' | sed -e 's/^v//')

          echo "Latest: $LATEST"
          echo "::set-output name=version::$(echo $LATEST)"
      - id: current
        name: Check current version
        run: |
          CURRENT=$(cat Dockerfile.slim | grep "ARG SBT_VERSION" | sed -e 's/^.*=\(.*\)$/\1/')

          echo "Current: $CURRENT"
          echo "::set-output name=version::$(echo $CURRENT)"
      - name: Update
        if: ${{ steps.latest.outputs.version != steps.current.outputs.version }}
        run: |
          sed -i 's/${{ steps.current.outputs.version }}/${{ steps.latest.outputs.version }}/g' Dockerfile.slim
          sed -i 's/${{ steps.current.outputs.version }}/${{ steps.latest.outputs.version }}/g' Dockerfile.full
      - name: Push
        if: ${{ steps.latest.outputs.version != steps.current.outputs.version }}
        uses: github-actions-x/commit@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'Chore: Update SBT to ${{ steps.latest.outputs.version }}'
          force-add: 'true'
          files: Dockerfile.slim Dockerfile.full
          name: 'Github Actions'
          email: 'danieletorelli@users.noreply.github.com'
      - name: Release
        if: ${{ steps.latest.outputs.version != steps.current.outputs.version }}
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.latest.outputs.version }}
          release_name: ${{ steps.latest.outputs.version }}
          draft: false
          prerelease: false
